project:
  type: website

website:
  title: "ISSS608-dex"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - href: Hands-on_Ex/Hands-on_Ex00.html
        text: "0. Hands-on Exercise 0"
      - href: Hands-on_Ex/Hands-on_Ex01.html
        text: "1. Hands-on Exercise 1"
      - href: Hands-on_Ex/Hands-on_Ex02.html
        text: "2. Hands-on Exercise 2"
      - href: Hands-on_Ex/Hands-on_Ex03.html
        text: "3. Hands-on Exercise 3"
      - href: Hands-on_Ex/Hands-on_Ex04.html
        text: "4. Hands-on Exercise 4"
      - href: Hands-on_Ex/Hands-on_Ex05.html
        text: "5. Hands-on Exercise 5"
      - href: Hands-on_Ex/Hands-on_Ex06.html
        text: "6. Hands-on Exercise 6"
      - href: Hands-on_Ex/Hands-on_Ex07.html
        text: "7. Hands-on Exercise 7"
      - href: Hands-on_Ex/Hands-on_Ex08.html
        text: "8. Hands-on Exercise 8"
      - href: Hands-on_Ex/Hands-on_Ex09.html
        text: "9. Hands-on Exercise 9"
    - text: "In-class Exercise"
      menu:
      - text: "1. Intro to Tableau"
        href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
      - text: "2. Creating Dashboards (Tableau)"
        href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
      - text: "3. Crafting Stories (Tableau)"
        href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
      - text: "4. Boxplot"
        href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
      - text: "5 Visual Analytics for Building Better Explanatory Models"
        href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
    - text: "Take-home Exercise"
      menu:
      - text: "1. Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
      - text: "2. Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html
    - text: "Project"
      menu:
      - text: "1. Project"
        href: Project/Project_01/Project.html
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual