project:
  type: website

website:
  title: "ISSS608-dex Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - href: Hands-on_Ex/Hands-on_Ex00.html
        text: "Hands-on Exercise 0"
      - href: Hands-on_Ex/Hands-on_Ex01.html
        text: "Hands-on Exercise 1"
      - href: Hands-on_Ex/Hands-on_Ex01.html
        text: "Hands-on Exercise 1"
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex/In-class_Ex01.html
      - text: "In-class Exercise 2"
        href: In-class_Ex/In-class_Ex02.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex01.html
      - text: "Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex02.html
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual