project:
  type: website

website:
  title: "ISSS608-dex"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - href: Hands-on_Ex/Hands-on_Ex00.html
        text: "Hands-on Exercise 0"
      - href: Hands-on_Ex/Hands-on_Ex01.html
        text: "Hands-on Exercise 1"
      - href: Hands-on_Ex/Hands-on_Ex02.html
        text: "Hands-on Exercise 2"
      - href: Hands-on_Ex/Hands-on_Ex03.html
        text: "Hands-on Exercise 3"
      - href: Hands-on_Ex/Hands-on_Ex04.html
        text: "Hands-on Exercise 4"
      - href: Hands-on_Ex/Hands-on_Ex05.html
        text: "Hands-on Exercise 5"
      - href: Hands-on_Ex/Hands-on_Ex06.html
        text: "Hands-on Exercise 6"
      - href: Hands-on_Ex/Hands-on_Ex07.html
        text: "Hands-on Exercise 7"
      - href: Hands-on_Ex/Hands-on_Ex08.html
        text: "Hands-on Exercise 8"
      - href: Hands-on_Ex/Hands-on_Ex09.html
        text: "Hands-on Exercise 9"
    - text: "In-class Exercise"
      menu:
      - text: "1. Intro to Tableau"
        href: https://public.tableau.com/views/In-class_Ex01_17371866977140/Dashboard1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "2. Creating Dashboards (Tableau)"
        href: https://public.tableau.com/views/In-class_Ex02_17377894914220/Dashboard1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
      - text: "3. Creating Stories (Tableau)"
        href: In-class_Ex/In-class_Ex03/In-class_Ex03.qmd
      - text: "4. Boxplot"
        href: In-class_Ex/In-class_Ex04/In-class_Ex04.qmd
      - text: "5 Visual Analytics for Building Better Explanatory Models"
        href: In-class_Ex/In-class_Ex05/In-class_Ex05.qmd
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
      - text: "Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual